name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Regular
            WITH_ASAN: "false"

          - name: Address_sanitizer
            WITH_ASAN: "true"

    name: ${{ matrix.name }}

    env:
      WITH_ASAN: ${{ matrix.WITH_ASAN }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      COVERALLS_SERVICE_NAME: "GitHub Actions"
      
    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Build
        run: |
            docker run \
            -e WORK_DIR="$PWD" \
            -e WITH_ASAN="${{ env.WITH_ASAN }}" \
            -e COVERALLS_REPO_TOKEN="${{ env.COVERALLS_REPO_TOKEN }}" \
            -e COVERALLS_SERVICE_NAME="${{ env.COVERALLS_SERVICE_NAME }}" \
            -e EVENT_NAME="${{ github.event_name }}" \
            -v $PWD:$PWD ubuntu:20.04 $PWD/.github/workflows/start.sh
